allowBuilds:
  "@prisma/engines": false
  esbuild: false
  prisma: false
  sharp: false
  unrs-resolver: false

minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - next
  - react

blockExoticSubdeps: true
trustPolicy: no-downgrade
