import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { NuqsAdapter } from "nuqs/adapters/next/app"
import { Toaster } from "sonner"

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
})

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NuqsAdapter>{children}</NuqsAdapter>
        {/*Toaster with custom success color and text and icons*/}
        <Toaster
          position="top-right"
          richColors
          toastOptions={{
            classNames: {
              success: "!bg-indigo-600 !text-white",
            },
          }}
          // icons={{
          //   success: <SuccessIcon />,
          //   info: <InfoIcon />,
          //   warning: <WarningIcon />,
          //   error: <ErrorIcon />,
          //   loading: <LoadingIcon />,
          // }}
        />
      </body>
    </html>
  )
}
