name: Migration of database for deployment

on:
  push:
    paths:
      - prisma/migrations/**
    branches:
      - main
  workflow_dispatch:

jobs:
  run-migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Node.js setup
        uses: actions/setup-node@v6
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install
      - name: Apply all the pending migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
